### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by mattmontero** [kkorolyov/133-Carpool#6]
Trying to figure out a way to implement notifications. So far, I created a Notifications interface to be implemented by SystemNotification, PassangerNotification, and DriverNotification. Each one really differs by who the message gets sent to, i.e. if its a system notification, most likely it will be sent to both drivers and passengers, then passengers are received by only passengers, and drivers only received by drivers. An issue comes up when a passenger or driver is to receive a message. If a passenger happens to have a driver state, the notifications will be distributed incorrectly. Any clue how to tackle this?

P.S. I'll be back on tomorrow, 3/5/16, after work around 6.

**Comment by kkorolyov** [comment]
Think this was solved a while back.
